{{- if and (not .Values.openTerminal.apiKey.existingSecret) .Values.openTerminal.apiKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-terminal.fullname" . }}-api-key
  labels:
    {{- include "open-terminal.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.openTerminal.apiKey.value | quote }}
{{- end }}
