---
{{- if .Values.ingresses.http.enabled -}}
{{- $fullName := include "adguard-home.fullname" . -}}
{{- $svcPort := .Values.services.http.port -}}
{{- if and .Values.ingresses.http.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingresses.http.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingresses.http.annotations "kubernetes.io/ingress.class" .Values.ingresses.http.className}}
  {{- end }}
{{- end -}}
{{if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{else }}
apiVersion: extensions/v1beta1
{{end -}}
kind: Ingress
metadata:
  name: {{ $fullName }}-http
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
  {{- with .Values.ingresses.http.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingresses.http.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingresses.http.className }}
  {{- end }}
  {{- if .Values.ingresses.http.tls }}
  tls:
    {{- range .Values.ingresses.http.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingresses.http.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-http
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-http
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}

---
{{- if .Values.ingresses.https.enabled -}}
{{- $fullName := include "adguard-home.fullname" . -}}
{{- $svcPort := .Values.services.https.port -}}
{{- if and .Values.ingresses.https.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingresses.https.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingresses.https.annotations "kubernetes.io/ingress.class" .Values.ingresses.https.className}}
  {{- end }}
{{- end -}}
{{if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{else }}
apiVersion: extensions/v1beta1
{{end -}}
kind: Ingress
metadata:
  name: {{ $fullName }}-https
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
  {{- with .Values.ingresses.https.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingresses.https.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingresses.https.className }}
  {{- end }}
  {{- if .Values.ingresses.https.tls }}
  tls:
    {{- range .Values.ingresses.https.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingresses.https.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-https
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-https
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
