{{- if or .Values.mariadb.enabled .Values.mongodb.enabled .Values.crawlers.engineeringblogs_xyz.cronjob.enabled .Values.crawlers.rm3l_org.cronjob.enabled .Values.crawlers.discoverdev_io.cronjob.enabled }}
{{- $kubeVersion := .Capabilities.KubeVersion.GitVersion -}}

{{- if .Values.crawlers.discoverdev_io.cronjob.enabled }}
{{/* discoverdev.io */}}
{{- if semverCompare ">=1.21-0" $kubeVersion -}}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "dev-feed.fullname" . }}-crawler-discoverdev-io
spec:
  schedule: "{{ .Values.crawlers.discoverdev_io.cronjob.schedule }}"
  concurrencyPolicy: {{ .Values.crawlers.discoverdev_io.cronjob.concurrencyPolicy }}
  startingDeadlineSeconds: {{ .Values.crawlers.discoverdev_io.cronjob.startingDeadlineSeconds }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.crawlers.discoverdev_io.cronjob.ttlSecondsAfterFinished }}
      activeDeadlineSeconds: {{ .Values.crawlers.discoverdev_io.cronjob.activeDeadlineSeconds }}
      template:
        metadata:
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
            checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
            {{- with .Values.crawlers.discoverdev_io.cronjob.podAnnotations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- with .Values.crawlers.discoverdev_io.cronjob.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.crawlers.discoverdev_io.cronjob.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
           {{- end }}
          serviceAccountName: {{ include "dev-feed.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.crawlers.discoverdev_io.cronjob.podSecurityContext | nindent 12 }}

          {{- if or .Values.mariadb.enabled .Values.mongodb.enabled }}
          initContainers:
          - name: wait-db-service
            image: busybox:1.28
            {{- if .Values.mariadb.enabled }}
            command: ['sh', '-c', "until nslookup {{ include "dev-feed.fullname" . }}-mariadb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for {{ include "dev-feed.fullname" . }}-mariadb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; sleep 2; done"]
            {{- else }}
            command: ['sh', '-c', "until nslookup {{ include "dev-feed.fullname" . }}-mongodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for {{ include "dev-feed.fullname" . }}-mongodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; sleep 2; done"]
            {{- end }}
            resources:
              limits:
                cpu: 100m
                memory: 10Mi
              requests:
                cpu: 100m
                memory: 1Mi
            securityContext:
              readOnlyRootFilesystem: true
              runAsUser: 65534
              runAsGroup: 65534
          {{- end }}

          containers:
          - name: {{ include "dev-feed.fullname" . }}-crawler-discoverdev-io
            image: "{{ .Values.crawlers.discoverdev_io.cronjob.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.crawlers.discoverdev_io.cronjob.image.pullPolicy }}
            securityContext:
              readOnlyRootFilesystem: true
              runAsUser: 65534
              runAsGroup: 65534
            env:
            {{- if or .Values.mongodb.enabled (eq "mongodb" .Values.datasource.type ) }}
            - name: DATASOURCE_MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "dev-feed.fullname" . }}
                  key: datasource.mongodb.connectionString
            {{- else }}
            - name: DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "dev-feed.fullname" . }}
                  key: datasource.user
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dev-feed.fullname" . }}
                  key: datasource.password
            {{- end }}
            args:
            {{- if or .Values.mongodb.enabled (eq "mongodb" .Values.datasource.type ) }}
            - mongo
            - --mongo-connection-string=$(DATASOURCE_MONGODB_CONNECTION_STRING)
            {{- else }}
            - rdbms
            - --datasource-jdbc-driver={{ include "dev-feed.datasourceDriver" . }}
            - --datasource-jdbc-url={{ include "dev-feed.datasourceUrl" . }}
            - --datasource-user=$(DATASOURCE_USER)
            - --datasource-password=$(DATASOURCE_PASSWORD)
            {{- end }}
            - --article-max-age-days={{ .Values.crawlers.discoverdev_io.cronjob.articleMaxAgeDays }}
            resources:
              {{- toYaml .Values.crawlers.discoverdev_io.cronjob.resources | nindent 14 }}
          restartPolicy: {{ .Values.crawlers.discoverdev_io.cronjob.restartPolicy }}

{{- end }}
---
{{- if .Values.crawlers.engineeringblogs_xyz.cronjob.enabled }}
{{/* engineeringblogs.xyz */}}
{{- if semverCompare ">=1.21-0" $kubeVersion -}}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "dev-feed.fullname" . }}-crawler-engineeringblogs-xyz
spec:
  schedule: "{{ .Values.crawlers.engineeringblogs_xyz.cronjob.schedule }}"
  concurrencyPolicy: {{ .Values.crawlers.engineeringblogs_xyz.cronjob.concurrencyPolicy }}
  startingDeadlineSeconds: {{ .Values.crawlers.engineeringblogs_xyz.cronjob.startingDeadlineSeconds }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.crawlers.engineeringblogs_xyz.cronjob.ttlSecondsAfterFinished }}
      activeDeadlineSeconds: {{ .Values.crawlers.engineeringblogs_xyz.cronjob.activeDeadlineSeconds }}
      template:
        metadata:
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
            checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
            {{- with .Values.crawlers.engineeringblogs_xyz.cronjob.podAnnotations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- with .Values.crawlers.engineeringblogs_xyz.cronjob.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.crawlers.engineeringblogs_xyz.cronjob.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
           {{- end }}
          serviceAccountName: {{ include "dev-feed.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.crawlers.engineeringblogs_xyz.cronjob.podSecurityContext | nindent 12 }}

          {{- if or .Values.mariadb.enabled .Values.mongodb.enabled }}
          initContainers:
          - name: wait-db-service
            image: busybox:1.28
            {{- if .Values.mariadb.enabled }}
            command: ['sh', '-c', "until nslookup {{ include "dev-feed.fullname" . }}-mariadb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for {{ include "dev-feed.fullname" . }}-mariadb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; sleep 2; done"]
            {{- else }}
            command: ['sh', '-c', "until nslookup {{ include "dev-feed.fullname" . }}-mongodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for {{ include "dev-feed.fullname" . }}-mongodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; sleep 2; done"]
            {{- end }}
            resources:
              limits:
                cpu: 100m
                memory: 10Mi
              requests:
                cpu: 100m
                memory: 1Mi
            securityContext:
              readOnlyRootFilesystem: true
              runAsUser: 65534
              runAsGroup: 65534
          {{- end }}

          containers:
          - name: {{ include "dev-feed.fullname" . }}-crawler-engineeringblogs-xyz
            image: "{{ .Values.crawlers.engineeringblogs_xyz.cronjob.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.crawlers.engineeringblogs_xyz.cronjob.image.pullPolicy }}
            securityContext:
              readOnlyRootFilesystem: true
              runAsUser: 65534
              runAsGroup: 65534
            env:
            {{- if or .Values.mongodb.enabled (eq "mongodb" .Values.datasource.type ) }}
            - name: DATASOURCE_MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "dev-feed.fullname" . }}
                  key: datasource.mongodb.connectionString
            {{- else }}
            - name: DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "dev-feed.fullname" . }}
                  key: datasource.user
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dev-feed.fullname" . }}
                  key: datasource.password
            {{- end }}
            args:
            {{- if or .Values.mongodb.enabled (eq "mongodb" .Values.datasource.type ) }}
            - mongo
            - --mongo-connection-string=$(DATASOURCE_MONGODB_CONNECTION_STRING)
            {{- else }}
            - rdbms
            - --datasource-jdbc-driver={{ include "dev-feed.datasourceDriver" . }}
            - --datasource-jdbc-url={{ include "dev-feed.datasourceUrl" . }}
            - --datasource-user=$(DATASOURCE_USER)
            - --datasource-password=$(DATASOURCE_PASSWORD)
            {{- end }}
            - --article-max-age-days={{ .Values.crawlers.engineeringblogs_xyz.cronjob.articleMaxAgeDays }}
            resources:
              {{- toYaml .Values.crawlers.engineeringblogs_xyz.cronjob.resources | nindent 14 }}
          restartPolicy: {{ .Values.crawlers.engineeringblogs_xyz.cronjob.restartPolicy }}
{{- end }}
---
{{- if .Values.crawlers.rm3l_org.cronjob.enabled }}
{{/* rm3l.org */}}
{{- if semverCompare ">=1.21-0" $kubeVersion -}}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "dev-feed.fullname" . }}-crawler-rm3l-org
spec:
  schedule: "{{ .Values.crawlers.rm3l_org.cronjob.schedule }}"
  concurrencyPolicy: {{ .Values.crawlers.rm3l_org.cronjob.concurrencyPolicy }}
  startingDeadlineSeconds: {{ .Values.crawlers.rm3l_org.cronjob.startingDeadlineSeconds }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.crawlers.rm3l_org.cronjob.ttlSecondsAfterFinished }}
      activeDeadlineSeconds: {{ .Values.crawlers.rm3l_org.cronjob.activeDeadlineSeconds }}
      template:
        metadata:
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
            checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
            {{- with .Values.crawlers.rm3l_org.cronjob.podAnnotations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- with .Values.crawlers.rm3l_org.cronjob.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.crawlers.rm3l_org.cronjob.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
           {{- end }}
          serviceAccountName: {{ include "dev-feed.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.crawlers.rm3l_org.cronjob.podSecurityContext | nindent 12 }}

          {{- if or .Values.mariadb.enabled .Values.mongodb.enabled }}
          initContainers:
          - name: wait-db-service
            image: busybox:1.28
            {{- if .Values.mariadb.enabled }}
            command: ['sh', '-c', "until nslookup {{ include "dev-feed.fullname" . }}-mariadb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for {{ include "dev-feed.fullname" . }}-mariadb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; sleep 2; done"]
            {{- else }}
            command: ['sh', '-c', "until nslookup {{ include "dev-feed.fullname" . }}-mongodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for {{ include "dev-feed.fullname" . }}-mongodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; sleep 2; done"]
            {{- end }}
            resources:
              limits:
                cpu: 100m
                memory: 10Mi
              requests:
                cpu: 100m
                memory: 1Mi
            securityContext:
              readOnlyRootFilesystem: true
              runAsUser: 65534
              runAsGroup: 65534
          {{- end }}

          containers:
          - name: {{ include "dev-feed.fullname" . }}-crawler-rm3l-org
            image: "{{ .Values.crawlers.rm3l_org.cronjob.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.crawlers.rm3l_org.cronjob.image.pullPolicy }}
            securityContext:
              readOnlyRootFilesystem: true
              runAsUser: 65534
              runAsGroup: 65534
            env:
            {{- if or .Values.mongodb.enabled (eq "mongodb" .Values.datasource.type ) }}
            - name: DATASOURCE_MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "dev-feed.fullname" . }}
                  key: datasource.mongodb.connectionString
            {{- else }}
            - name: DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "dev-feed.fullname" . }}
                  key: datasource.user
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dev-feed.fullname" . }}
                  key: datasource.password
            {{- end }}
            args:
            {{- if or .Values.mongodb.enabled (eq "mongodb" .Values.datasource.type ) }}
            - mongo
            - --mongo-connection-string=$(DATASOURCE_MONGODB_CONNECTION_STRING)
            {{- else }}
            - rdbms
            - --datasource-jdbc-driver={{ include "dev-feed.datasourceDriver" . }}
            - --datasource-jdbc-url={{ include "dev-feed.datasourceUrl" . }}
            - --datasource-user=$(DATASOURCE_USER)
            - --datasource-password=$(DATASOURCE_PASSWORD)
            {{- end }}
            - --article-max-age-days={{ .Values.crawlers.rm3l_org.cronjob.articleMaxAgeDays }}
            resources:
              {{- toYaml .Values.crawlers.rm3l_org.cronjob.resources | nindent 14 }}
          restartPolicy: {{ .Values.crawlers.rm3l_org.cronjob.restartPolicy }}
{{- end }}
{{- end }}
