apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atuin.fullname" . }}
  labels:
    {{- include "atuin.labels" . | nindent 4 }}
data:
  ATUIN_DB_URI: {{ include "atuin.postgresqlConnectionString" . | b64enc | quote }}
