apiVersion: v1
kind: Service
metadata:
  name: {{ include "atuin.fullname" . }}
  labels:
    {{- include "atuin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: app-port
      protocol: TCP
      name: app-port
  selector:
    {{- include "atuin.selectorLabels" . | nindent 4 }}
